using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using CompaniesHouse.SourceGenerator;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using Shouldly;
using Xunit;

namespace CompaniesHouse.SourceGenerator.Tests
{
    /// <summary>
    /// Full-source "snapshot" tests: given a small fixed YAML input, assert the entire
    /// generated file content matches byte-for-byte (rather than spot-checking a handful
    /// of lines like <see cref="EnumValueTypeGeneratorTests"/>). Guards against accidental
    /// whitespace/shape regressions in <see cref="ValueTypeEmitter"/> - see plan 10
    /// (testing strategy), "Generator snapshot tests".
    /// </summary>
    public class ValueTypeEmitterSnapshotTests
    {
        [Fact]
        public void GeneratesTheExpectedValueTypeSourceForASimpleGroup()
        {
            var additionalFiles = new[]
            {
                new InMemoryAdditionalText(@"external\api-enumerations\constants.yml", """
                    widget_state:
                        'on' : "On"
                        'off' : "Off"
                    """),
                new InMemoryAdditionalText(@"enum-map.txt", "widget_state|CompaniesHouse.Snapshot|WidgetState|true"),
            };

            var generated = RunGenerator(additionalFiles);

            generated["WidgetState.g.cs"].ShouldBe(
                """
                // <auto-generated/>
                // Generated by CompaniesHouse.SourceGenerator from the api-enumerations
                // submodule and enumerations/extra overlay. Do not hand-edit - see
                // .plans/completed/04-enum-source-generator.md.
                #nullable enable

                using System;
                using System.Collections.Generic;
                using System.Text.Json.Serialization;
                using CompaniesHouse.JsonConverters;

                namespace CompaniesHouse.Snapshot
                {
                    [JsonConverter(typeof(WidgetStateJsonConverter))]
                    public readonly record struct WidgetState
                    {
                        private readonly string? _value;

                        public WidgetState(string? value)
                        {
                            _value = value;
                        }

                        public string Value => _value ?? string.Empty;

                        public bool HasValue => !string.IsNullOrEmpty(_value);

                        public bool IsKnown => KnownValues.Contains(Value);

                        public string? Description => Descriptions.TryGetValue(Value, out var description) ? description : null;

                        public static WidgetState On => new("on");
                        public static WidgetState Off => new("off");

                        public override string ToString() => Value;

                        private static readonly HashSet<string> KnownValues = new(StringComparer.Ordinal)
                        {
                            "on",
                            "off",
                        };

                        private static readonly IReadOnlyDictionary<string, string> Descriptions = new Dictionary<string, string>(StringComparer.Ordinal)
                        {
                            ["on"] = "On",
                            ["off"] = "Off",
                        };
                    }
                }

                """,
                StringCompareShould.IgnoreLineEndings);

            generated["WidgetStateJsonConverter.g.cs"].ShouldBe(
                """
                // <auto-generated/>
                // Generated by CompaniesHouse.SourceGenerator - do not hand-edit.
                #nullable enable

                using System;
                using System.Text.Json;
                using System.Text.Json.Serialization;
                using CompaniesHouse.Snapshot;

                namespace CompaniesHouse.JsonConverters
                {
                    public sealed class WidgetStateJsonConverter : JsonConverter<WidgetState>
                    {
                        public override WidgetState Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
                        {
                            if (reader.TokenType == JsonTokenType.Null)
                            {
                                return default;
                            }

                            return new WidgetState(reader.GetString());
                        }

                        public override void Write(Utf8JsonWriter writer, WidgetState value, JsonSerializerOptions options)
                        {
                            if (!value.HasValue)
                            {
                                writer.WriteNullValue();
                                return;
                            }

                            writer.WriteStringValue(value.Value);
                        }
                    }
                }

                """,
                StringCompareShould.IgnoreLineEndings);
        }

        private static Dictionary<string, string> RunGenerator(IEnumerable<InMemoryAdditionalText> additionalFiles)
        {
            var compilation = CSharpCompilation.Create(
                "CompaniesHouse.SourceGenerator.Tests.SnapshotAssembly",
                references: new[]
                {
                    MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
                },
                options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

            var generator = new EnumValueTypeGenerator();
            GeneratorDriver driver = CSharpGeneratorDriver.Create(new IIncrementalGenerator[] { generator });
            driver = driver.AddAdditionalTexts(additionalFiles.Cast<AdditionalText>().ToImmutableArray());

            driver = driver.RunGeneratorsAndUpdateCompilation(compilation, out _, out var runDiagnostics);
            var runResult = driver.GetRunResult();

            var faulted = runResult.Results.FirstOrDefault(r => r.Exception is not null);
            if (faulted.Exception is not null)
            {
                throw faulted.Exception;
            }

            if (runDiagnostics.Any())
            {
                throw new System.Exception("Generator diagnostics: " + string.Join("\n", runDiagnostics));
            }

            return runResult.Results
                .Where(r => !r.GeneratedSources.IsDefault)
                .SelectMany(r => r.GeneratedSources)
                .ToDictionary(s => s.HintName, s => s.SourceText.ToString());
        }
    }
}
