using System;
using System.Collections.Generic;
using System.Text;

namespace CompaniesHouse.SourceGenerator
{
    /// <summary>
    /// Emits the C# source for a single enum group, matching the frozen string-backed value
    /// type shape established in <c>src/CompaniesHouse/Response/CompanyStatus.cs</c> (plan 03).
    /// </summary>
    internal static class ValueTypeEmitter
    {
        /// <summary>Emits the <c>readonly record struct</c> value type.</summary>
        public static string EmitValueType(EnumMapEntry entry, MergedGroup group)
        {
            var members = BuildMembers(group);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// Generated by CompaniesHouse.SourceGenerator from the api-enumerations");
            sb.AppendLine("// submodule and enumerations/extra overlay. Do not hand-edit - see");
            sb.AppendLine("// .plans/completed/04-enum-source-generator.md.");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Text.Json.Serialization;");
            sb.AppendLine("using CompaniesHouse.JsonConverters;");
            sb.AppendLine();
            sb.AppendLine($"namespace {entry.Namespace}");
            sb.AppendLine("{");
            sb.AppendLine($"    [JsonConverter(typeof({entry.TypeName}JsonConverter))]");
            sb.AppendLine($"    public readonly record struct {entry.TypeName}");
            sb.AppendLine("    {");
            sb.AppendLine("        private readonly string? _value;");
            sb.AppendLine();
            sb.AppendLine($"        public {entry.TypeName}(string? value)");
            sb.AppendLine("        {");
            sb.AppendLine("            _value = value;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public string Value => _value ?? string.Empty;");
            sb.AppendLine();
            sb.AppendLine("        public bool HasValue => !string.IsNullOrEmpty(_value);");
            sb.AppendLine();
            sb.AppendLine("        public bool IsKnown => KnownValues.Contains(Value);");
            sb.AppendLine();

            if (entry.IncludeDescriptions)
            {
                sb.AppendLine("        public string? Description => Descriptions.TryGetValue(Value, out var description) ? description : null;");
                sb.AppendLine();
            }

            foreach (var (memberName, wireValue) in members)
            {
                sb.AppendLine($"        public static {entry.TypeName} {memberName} => new(\"{Escape(wireValue)}\");");
            }

            sb.AppendLine();
            sb.AppendLine("        public override string ToString() => Value;");
            sb.AppendLine();
            sb.AppendLine("        private static readonly HashSet<string> KnownValues = new(StringComparer.Ordinal)");
            sb.AppendLine("        {");
            foreach (var (_, wireValue) in members)
            {
                sb.AppendLine($"            \"{Escape(wireValue)}\",");
            }
            sb.AppendLine("        };");

            if (entry.IncludeDescriptions)
            {
                sb.AppendLine();
                sb.AppendLine("        private static readonly IReadOnlyDictionary<string, string> Descriptions = new Dictionary<string, string>(StringComparer.Ordinal)");
                sb.AppendLine("        {");
                foreach (var wireValue in group.WireValues)
                {
                    sb.AppendLine($"            [\"{Escape(wireValue)}\"] = \"{Escape(group.GetDescription(wireValue))}\",");
                }
                sb.AppendLine("        };");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        /// <summary>Emits the companion <see cref="System.Text.Json.Serialization.JsonConverter{T}"/>.</summary>
        public static string EmitJsonConverter(EnumMapEntry entry)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// Generated by CompaniesHouse.SourceGenerator - do not hand-edit.");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Text.Json;");
            sb.AppendLine("using System.Text.Json.Serialization;");
            sb.AppendLine($"using {entry.Namespace};");
            sb.AppendLine();
            sb.AppendLine("namespace CompaniesHouse.JsonConverters");
            sb.AppendLine("{");
            sb.AppendLine($"    public sealed class {entry.TypeName}JsonConverter : JsonConverter<{entry.TypeName}>");
            sb.AppendLine("    {");
            sb.AppendLine($"        public override {entry.TypeName} Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (reader.TokenType == JsonTokenType.Null)");
            sb.AppendLine("            {");
            sb.AppendLine("                return default;");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine($"            return new {entry.TypeName}(reader.GetString());");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine($"        public override void Write(Utf8JsonWriter writer, {entry.TypeName} value, JsonSerializerOptions options)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (!value.HasValue)");
            sb.AppendLine("            {");
            sb.AppendLine("                writer.WriteNullValue();");
            sb.AppendLine("                return;");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            writer.WriteStringValue(value.Value);");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        /// <summary>
        /// Builds the ordered, de-duplicated (member name, wire value) pairs for a group, skipping
        /// an empty-string wire value (which is represented by the type's absent/default state - see
        /// plan 03 - rather than a static member).
        /// </summary>
        private static List<(string MemberName, string WireValue)> BuildMembers(MergedGroup group)
        {
            var members = new List<(string MemberName, string WireValue)>();
            var usedNames = new HashSet<string>(StringComparer.Ordinal);

            foreach (var wireValue in group.WireValues)
            {
                if (wireValue.Length == 0)
                {
                    continue;
                }

                var memberName = MemberNameGenerator.ToMemberName(wireValue);
                if (!usedNames.Add(memberName))
                {
                    throw new InvalidOperationException(
                        $"CompaniesHouse.SourceGenerator: generated member name '{memberName}' for group " +
                        $"'{group.Name}' collides with another wire value. Add an override in " +
                        $"{nameof(MemberNameGenerator)}.");
                }

                members.Add((memberName, wireValue));
            }

            return members;
        }

        private static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
